version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --with docs --no-root

formats:
  - pdf
  - epub

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
